/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/clientes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar clientes */
        get: operations["list_clientes"];
        put?: never;
        /** Crear cliente */
        post: operations["create_cliente"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clientes/buscar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Buscar clientes por apellido (parcial) o NIF/DNI (exacto) */
        get: operations["buscar_clientes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clientes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener cliente con sus vehículos */
        get: operations["get_cliente"];
        /** Actualizar cliente */
        put: operations["update_cliente"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vehiculos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Crear vehículo (requiere cliente_id) */
        post: operations["create_vehiculo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vehiculos/buscar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Buscar vehículo por matrícula */
        get: operations["buscar_vehiculo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vehiculos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener vehículo con historial de órdenes */
        get: operations["get_vehiculo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ordenes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar órdenes para el tablero Kanban
         * @description Devuelve las órdenes en estados no terminales (recibida, presupuestado, en_reparacion, finalizada) más las órdenes en estados terminales (entregado, rechazado) de los últimos 7 días.
         */
        get: operations["list_ordenes"];
        put?: never;
        /**
         * Crear orden de trabajo (requiere vehiculo_id)
         * @description Crea una nueva orden en estado `recibida`. Solo puede existir una orden activa (no terminal) por vehículo a la vez.
         */
        post: operations["create_orden"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ordenes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener detalle completo de una orden (con items) */
        get: operations["get_orden"];
        /**
         * Actualizar campos editables de la orden
         * @description Solo edita `descripcion`, `kilometraje` y `notas_internas`. No puede modificar órdenes en estados terminales.
         */
        put: operations["update_orden"];
        post?: never;
        /** Eliminar orden (solo si estado = recibida) */
        delete: operations["delete_orden"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ordenes/{id}/estado": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Cambiar estado de la orden
         * @description Valida la transición según la máquina de estados. Al rechazar desde `presupuestado`, el backend crea automáticamente un BudgetItem de diagnóstico (30 min a tarifa_hora). Al rechazar desde `en_reparacion`, se deben enviar los items de cancelación en el cuerpo.
         */
        patch: operations["cambiar_estado_orden"];
        trace?: never;
    };
    "/ordenes/{id}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Añadir item al presupuesto de la orden */
        post: operations["add_item"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ordenes/{id}/items/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Editar item del presupuesto
         * @description Los items con `es_cargo_cancelacion=false` no son editables cuando el estado de la orden es `en_reparacion`, `finalizada`, `entregado` o `rechazado`.
         */
        put: operations["update_item"];
        post?: never;
        /**
         * Eliminar item del presupuesto
         * @description Los items con `es_cargo_cancelacion=false` no son eliminables cuando el estado de la orden es `en_reparacion`, `finalizada`, `entregado` o `rechazado`.
         */
        delete: operations["delete_item"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ordenes/{id}/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Descargar PDF de la orden (factura o factura de cancelación)
         * @description Genera y devuelve el PDF correspondiente a la orden. Si el estado es `entregado` genera la factura normal (items normales + IVA 21%). Si el estado es `rechazado` genera la factura de cancelación (items de cancelación + IVA 21%). Solo disponible para estados terminales (`entregado` o `rechazado`).
         */
        get: operations["get_orden_pdf"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener configuración del taller */
        get: operations["get_config"];
        /**
         * Actualizar configuración del taller
         * @description Hace upsert de cada clave recibida. Las claves no incluidas en el cuerpo no se modifican.
         */
        put: operations["update_config"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorDetail: {
            /**
             * @description Mensaje descriptivo del error
             * @example No se puede eliminar una orden que no está en estado 'recibida'
             */
            detail: string;
        };
        /**
         * @example recibida
         * @enum {string}
         */
        EstadoOrden: "recibida" | "presupuestado" | "en_reparacion" | "finalizada" | "entregado" | "rechazado";
        /**
         * @example mano_obra
         * @enum {string}
         */
        TipoItem: "mano_obra" | "pieza";
        ClienteBase: {
            /** @example Juan */
            nombre: string;
            /** @example García López */
            apellido: string;
            /** @example 12345678A */
            nif_dni: string;
            /** @example 612345678 */
            telefono: string;
            /**
             * Format: email
             * @example juan.garcia@email.com
             */
            email?: string | null;
            /** @example Calle Mayor 15, 2ºA */
            direccion: string;
            /** @example Madrid */
            localidad: string;
            /** @example Madrid */
            provincia: string;
        };
        ClienteCreate: components["schemas"]["ClienteBase"];
        /** @description Todos los campos son opcionales en la actualización */
        ClienteUpdate: {
            /** @example Juan */
            nombre?: string;
            /** @example García López */
            apellido?: string;
            /** @example 12345678A */
            nif_dni?: string;
            /** @example 612345678 */
            telefono?: string;
            /**
             * Format: email
             * @example juan.garcia@email.com
             */
            email?: string | null;
            /** @example Calle Mayor 15, 2ºA */
            direccion?: string;
            /** @example Madrid */
            localidad?: string;
            /** @example Madrid */
            provincia?: string;
        };
        Cliente: components["schemas"]["ClienteBase"] & {
            /** @example 1 */
            id: number;
        };
        ClienteConVehiculos: components["schemas"]["Cliente"] & {
            vehiculos: components["schemas"]["Vehicle"][];
        };
        VehicleBase: {
            /** @example 1 */
            cliente_id: number;
            /** @example 1234ABC */
            matricula: string;
            /** @example Seat */
            marca: string;
            /** @example León */
            modelo: string;
            /** @example 2019 */
            "a\u00F1o": number;
        };
        VehicleCreate: components["schemas"]["VehicleBase"];
        Vehicle: components["schemas"]["VehicleBase"] & {
            /** @example 1 */
            id: number;
        };
        VehicleConHistorial: components["schemas"]["Vehicle"] & {
            cliente: components["schemas"]["Cliente"];
            ordenes: components["schemas"]["OrderResumen"][];
        };
        OrderBase: {
            /** @example 1 */
            vehiculo_id: number;
            /** @example El motor hace un ruido extraño al arrancar en frío */
            descripcion: string;
            /** @example 85000 */
            kilometraje?: number | null;
            /** @example Revisar también el aceite porque el cliente mencionó consumo elevado */
            notas_internas?: string | null;
        };
        OrderCreate: components["schemas"]["OrderBase"];
        /** @description Solo se pueden editar descripcion, kilometraje y notas_internas */
        OrderUpdate: {
            /** @example El motor hace un ruido extraño al arrancar en frío */
            descripcion?: string;
            /** @example 85000 */
            kilometraje?: number | null;
            /** @example Revisar también el aceite */
            notas_internas?: string | null;
        };
        Order: {
            /** @example 1 */
            id: number;
            /** @example 2026-001 */
            numero_orden: string;
            /** @example 1 */
            vehiculo_id: number;
            estado: components["schemas"]["EstadoOrden"];
            /** @example El motor hace un ruido extraño al arrancar en frío */
            descripcion: string;
            /** @example 85000 */
            kilometraje?: number | null;
            /** @example Revisar también el aceite */
            notas_internas?: string | null;
            /**
             * Format: date-time
             * @example 2026-06-13T09:30:00
             */
            fecha_entrada: string;
            /**
             * Format: date-time
             * @example 2026-06-13T14:00:00
             */
            fecha_actualizacion: string;
            /**
             * Format: date-time
             * @example 2026-06-14T17:00:00
             */
            fecha_entrega?: string | null;
            vehiculo?: components["schemas"]["VehicleConCliente"];
            items: components["schemas"]["BudgetItem"][];
            /**
             * Format: float
             * @description Suma de cantidad × precio_unitario de todos los items (calculado en runtime)
             * @example 285.5
             */
            total?: number;
        };
        /** @description Versión resumida de la orden para el Kanban (sin items detallados) */
        OrderResumen: {
            /** @example 1 */
            id: number;
            /** @example 2026-001 */
            numero_orden: string;
            /** @example 1 */
            vehiculo_id: number;
            estado: components["schemas"]["EstadoOrden"];
            /** @example El motor hace un ruido extraño al arrancar en frío */
            descripcion: string;
            /** @example 85000 */
            kilometraje?: number | null;
            /** @example null */
            notas_internas?: string | null;
            /**
             * Format: date-time
             * @example 2026-06-13T09:30:00
             */
            fecha_entrada: string;
            /**
             * Format: date-time
             * @example 2026-06-13T14:00:00
             */
            fecha_actualizacion: string;
            /**
             * Format: date-time
             * @example null
             */
            fecha_entrega?: string | null;
            vehiculo?: components["schemas"]["VehicleConCliente"];
            /**
             * Format: float
             * @description Total del presupuesto calculado en runtime
             * @example 285.5
             */
            total?: number;
        };
        EstadoTransition: {
            estado: components["schemas"]["EstadoOrden"];
            /** @description Solo requerido al rechazar desde `en_reparacion`. Lista de items reales de cancelación (se guardan con es_cargo_cancelacion=true). */
            items_cancelacion?: components["schemas"]["BudgetItemCreate"][];
        };
        BudgetItemBase: {
            /** @example Cambio de filtro de aceite */
            concepto: string;
            tipo: components["schemas"]["TipoItem"];
            /**
             * Format: float
             * @example 1.5
             */
            cantidad: number;
            /**
             * Format: float
             * @example 45
             */
            precio_unitario: number;
            /**
             * @default false
             * @example false
             */
            es_cargo_cancelacion: boolean;
        };
        BudgetItemCreate: components["schemas"]["BudgetItemBase"];
        /** @description Todos los campos son opcionales en la actualización */
        BudgetItemUpdate: {
            /** @example Cambio de filtro de aceite */
            concepto?: string;
            tipo?: components["schemas"]["TipoItem"];
            /**
             * Format: float
             * @example 2
             */
            cantidad?: number;
            /**
             * Format: float
             * @example 45
             */
            precio_unitario?: number;
        };
        BudgetItem: components["schemas"]["BudgetItemBase"] & {
            /** @example 1 */
            id: number;
            /** @example 1 */
            order_id: number;
            /**
             * Format: float
             * @description cantidad × precio_unitario (calculado en runtime)
             * @example 67.5
             */
            subtotal?: number;
        };
        VehicleConCliente: components["schemas"]["Vehicle"] & {
            cliente: components["schemas"]["Cliente"];
        };
        /**
         * @description Mapa clave-valor de la configuración del taller. Claves conocidas: tarifa_hora, nombre_taller, cif_taller, direccion_taller. El valor siempre se almacena como texto.
         * @example {
         *       "tarifa_hora": "45.00",
         *       "nombre_taller": "Taller García",
         *       "cif_taller": "B12345678",
         *       "direccion_taller": "Calle Mayor 1, Madrid"
         *     }
         */
        ConfigMap: {
            [key: string]: string;
        };
    };
    responses: {
        /** @description Recurso no encontrado */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "detail": "Recurso no encontrado"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorDetail"];
            };
        };
        /** @description Petición inválida */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "detail": "Datos de entrada inválidos"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorDetail"];
            };
        };
        /** @description Violación de regla de negocio */
        BusinessRuleError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "detail": "No se puede cambiar el estado de una orden en estado terminal"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorDetail"];
            };
        };
    };
    parameters: {
        PathId: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_clientes: {
        parameters: {
            query?: {
                /** @description Búsqueda por nombre o apellido (parcial, case-insensitive) */
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de clientes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cliente"][];
                };
            };
        };
    };
    create_cliente: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClienteCreate"];
            };
        };
        responses: {
            /** @description Cliente creado */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cliente"];
                };
            };
            400: components["responses"]["BadRequest"];
            422: components["responses"]["BusinessRuleError"];
        };
    };
    buscar_clientes: {
        parameters: {
            query?: {
                /** @description Búsqueda parcial case-insensitive por apellido */
                apellido?: string;
                /** @description Búsqueda exacta por NIF o DNI */
                nif_dni?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de clientes que coinciden con la búsqueda */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cliente"][];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    get_cliente: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Detalle del cliente con vehículos asociados */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClienteConVehiculos"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    update_cliente: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClienteUpdate"];
            };
        };
        responses: {
            /** @description Cliente actualizado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cliente"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["BusinessRuleError"];
        };
    };
    create_vehiculo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VehicleCreate"];
            };
        };
        responses: {
            /** @description Vehículo creado */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Vehicle"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description Cliente no encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            422: components["responses"]["BusinessRuleError"];
        };
    };
    buscar_vehiculo: {
        parameters: {
            query: {
                /** @description Matrícula exacta (case-insensitive) */
                matricula: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Vehículo con historial de órdenes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VehicleConHistorial"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    get_vehiculo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Detalle del vehículo con historial completo de órdenes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VehicleConHistorial"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    list_ordenes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de órdenes para el Kanban */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderResumen"][];
                };
            };
        };
    };
    create_orden: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderCreate"];
            };
        };
        responses: {
            /** @description Orden creada */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description Vehículo no encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            422: components["responses"]["BusinessRuleError"];
        };
    };
    get_orden: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Orden completa con items de presupuesto */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    update_orden: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderUpdate"];
            };
        };
        responses: {
            /** @description Orden actualizada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
            404: components["responses"]["NotFound"];
            422: components["responses"]["BusinessRuleError"];
        };
    };
    delete_orden: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Orden eliminada correctamente */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
            422: components["responses"]["BusinessRuleError"];
        };
    };
    cambiar_estado_orden: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EstadoTransition"];
            };
        };
        responses: {
            /** @description Estado actualizado correctamente */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
            404: components["responses"]["NotFound"];
            422: components["responses"]["BusinessRuleError"];
        };
    };
    add_item: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BudgetItemCreate"];
            };
        };
        responses: {
            /** @description Item añadido */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BudgetItem"];
                };
            };
            404: components["responses"]["NotFound"];
            422: components["responses"]["BusinessRuleError"];
        };
    };
    update_item: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathId"];
                item_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BudgetItemUpdate"];
            };
        };
        responses: {
            /** @description Item actualizado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BudgetItem"];
                };
            };
            404: components["responses"]["NotFound"];
            422: components["responses"]["BusinessRuleError"];
        };
    };
    delete_item: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathId"];
                item_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Item eliminado correctamente */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
            422: components["responses"]["BusinessRuleError"];
        };
    };
    get_orden_pdf: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Fichero PDF generado */
            200: {
                headers: {
                    /** @description Nombre del fichero descargado */
                    "Content-Disposition"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": string;
                };
            };
            404: components["responses"]["NotFound"];
            422: components["responses"]["BusinessRuleError"];
        };
    };
    get_config: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Mapa clave-valor con la configuración actual */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "tarifa_hora": "45.00",
                     *       "nombre_taller": "Taller García",
                     *       "cif_taller": "B12345678",
                     *       "direccion_taller": "Calle Mayor 1, Madrid"
                     *     }
                     */
                    "application/json": components["schemas"]["ConfigMap"];
                };
            };
        };
    };
    update_config: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "tarifa_hora": "50.00",
                 *       "nombre_taller": "Taller García e Hijos"
                 *     }
                 */
                "application/json": components["schemas"]["ConfigMap"];
            };
        };
        responses: {
            /** @description Configuración actualizada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigMap"];
                };
            };
            400: components["responses"]["BadRequest"];
            422: components["responses"]["BusinessRuleError"];
        };
    };
}
